default: &default
  adapter: mysql2
  database: sys
  encoding: utf8
  host: <%= ENV["MYSQL_HOST"] %>
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>

development:
  <<: *default
